from pydantic import BaseModel
from typing import Optional

class DashboardData(BaseModel):
    diet: str
    ethnic_group: str
    hours_per_week_university_work: float
    family_earning_class: str
    quality_of_life: str
    alcohol_consumption: str
    personality_type: str
    stress_in_general: str
    well_hydrated: str
    exercise_per_week: float
    known_disabilities: str
    work_hours_per_week: float
    financial_support: str
    form_of_employment: str
    financial_problems: str
    home_country: str
    age: float
    course_of_study: str
    stress_before_exams: str
    feel_afraid: str
    timetable_preference: str
    timetable_reasons: str
    timetable_impact: str
    total_device_hours: float
    hours_socialmedia: float
    level_of_study: str
    gender: str
    physical_activities: str
    hours_between_lectures: float
    hours_per_week_lectures: float
    hours_socialising: float
    actual: str
    student_type_time: str
    student_type_location: str
    cost_of_study: float
    sense_of_belonging: str
    mental_health_activities: str
    predictions: float
    captured_at: str
    
class DashboardDataModel(BaseModel):
    diet: Optional[str]
    ethnic_group: Optional[str]
    hours_per_week_university_work: Optional[int]
    family_earning_class: Optional[str]
    quality_of_life: Optional[str]
    alcohol_consumption: Optional[str]
    personality_type: Optional[str]
    stress_in_general: Optional[str]
    well_hydrated: Optional[str]
    exercise_per_week: Optional[int]
    known_disabilities: Optional[str]
    work_hours_per_week: Optional[int]
    financial_support: Optional[str]
    form_of_employment: Optional[str]
    financial_problems: Optional[str]
    home_country: Optional[str]
    age: Optional[int]
    course_of_study: Optional[str]
    stress_before_exams: Optional[str]
    feel_afraid: Optional[str]
    timetable_preference: Optional[str]
    timetable_reasons: Optional[str]
    timetable_impact: Optional[str]
    total_device_hours: Optional[int]
    hours_socialmedia: Optional[int]
    level_of_study: Optional[str]
    gender: Optional[str]
    physical_activities: Optional[str]
    hours_between_lectures: Optional[int]
    hours_per_week_lectures: Optional[int]
    hours_socialising: Optional[int]
    actual: Optional[str]
    student_type_time: Optional[str]
    student_type_location: Optional[str]
    cost_of_study: Optional[int]
    sense_of_belonging: Optional[str]
    mental_health_activities: Optional[str]
    source: Optional[str]
    predictions: Optional[int]
    captured_at: Optional[str]